name: Build and Run Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-cnn-app:latest

    - name: Run Docker image
      run: |
        docker run -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/my-cnn-app:latest
        docker ps
        docker logs $(docker ps -q --filter "ancestor=${{ secrets.DOCKER_USERNAME }}/my-cnn-app:latest")
